CREATE TABLE tblWallet
(
EMAILID		VARCHAR(50)		NOT NULL,
PWD		VARCHAR(10)		NOT NULL,
NAME		VARCHAR(20)		NOT NULL,
PHONE		NUMERIC(18,0),
BANKACCNO	VARCHAR(15)		NOT NULL,
WALLETBAL	INT
PRIMARY KEY(EMAILID)
);


CREATE TABLE tblCustomerAccount
(
ACCOUNTNO	VARCHAR(15)	NOT NULL,
BALANCE		INT,
EMAILID		VARCHAR(50)	FOREIGN KEY REFERENCES tblWallet(EMAILID)		
);

